# Generated by Django 6.0.4 on 2026-04-16 19:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الرباعي')),
                ('national_id', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='يجب أن يكون السجل المدني 10 أرقام.', regex='^\\d{10}$')], verbose_name='السجل المدني')),
                ('school_name', models.CharField(max_length=255, verbose_name='اسم المدرسة')),
                ('sector', models.CharField(max_length=100, verbose_name='القطاع')),
                ('stage', models.CharField(choices=[('ابتدائي', 'ابتدائي'), ('متوسط', 'متوسط'), ('ثانوي', 'ثانوي'), ('رياض أطفال', 'رياض أطفال'), ('مجمع', 'مجمع'), ('أخرى', 'أخرى')], max_length=50, verbose_name='المرحلة الدراسية')),
                ('school_gender', models.CharField(choices=[('بنين', 'بنين'), ('بنات', 'بنات')], max_length=10, verbose_name='نوع المدرسة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('role', models.CharField(choices=[('مدير', 'مدير'), ('مديرة', 'مديرة')], max_length=10, verbose_name='الصفة')),
                ('performance_file', models.FileField(upload_to='performance_forms/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='استمارة الأداء الوظيفي')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.supervisor', verbose_name='المشرف')),
            ],
            options={
                'verbose_name': 'سجل مدير/مديرة',
                'verbose_name_plural': 'سجلات المديرين/المديرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VicePrincipalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الرباعي')),
                ('national_id', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='يجب أن يكون السجل المدني 10 أرقام.', regex='^\\d{10}$')], verbose_name='السجل المدني')),
                ('school_name', models.CharField(max_length=255, verbose_name='اسم المدرسة')),
                ('sector', models.CharField(max_length=100, verbose_name='القطاع')),
                ('stage', models.CharField(choices=[('ابتدائي', 'ابتدائي'), ('متوسط', 'متوسط'), ('ثانوي', 'ثانوي'), ('رياض أطفال', 'رياض أطفال'), ('مجمع', 'مجمع'), ('أخرى', 'أخرى')], max_length=50, verbose_name='المرحلة الدراسية')),
                ('school_gender', models.CharField(choices=[('بنين', 'بنين'), ('بنات', 'بنات')], max_length=10, verbose_name='نوع المدرسة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('role', models.CharField(choices=[('وكيل', 'وكيل'), ('وكيلة', 'وكيلة')], max_length=10, verbose_name='الصفة')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.supervisor', verbose_name='المشرف')),
            ],
            options={
                'verbose_name': 'سجل وكيل/وكيلة',
                'verbose_name_plural': 'سجلات الوكلاء/الوكيلات',
                'ordering': ['-created_at'],
            },
        ),
    ]
