# Generated by Django 6.0.4 on 2026-04-17 18:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('staffdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('principal', 'مدير/مديرة'), ('vice', 'وكيل/وكيلة')], max_length=20, verbose_name='نوع السجل')),
                ('reason', models.TextField(verbose_name='سبب طلب التصحيح')),
                ('requested_full_name', models.CharField(max_length=255, verbose_name='الاسم الرباعي المقترح')),
                ('requested_national_id', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='يجب أن يكون السجل المدني 10 أرقام.', regex='^\\d{10}$')], verbose_name='السجل المدني المقترح')),
                ('requested_school_name', models.CharField(max_length=255, verbose_name='اسم المدرسة المقترح')),
                ('requested_sector', models.CharField(max_length=100, verbose_name='القطاع المقترح')),
                ('requested_stage', models.CharField(choices=[('ابتدائي', 'ابتدائي'), ('متوسط', 'متوسط'), ('ثانوي', 'ثانوي'), ('رياض أطفال', 'رياض أطفال'), ('مجمع', 'مجمع'), ('أخرى', 'أخرى')], max_length=50, verbose_name='المرحلة الدراسية المقترحة')),
                ('requested_school_gender', models.CharField(choices=[('بنين', 'بنين'), ('بنات', 'بنات')], max_length=10, verbose_name='نوع المدرسة المقترح')),
                ('requested_role', models.CharField(max_length=10, verbose_name='الصفة المقترحة')),
                ('requested_notes', models.TextField(blank=True, verbose_name='الملاحظات المقترحة')),
                ('requested_performance_file', models.FileField(blank=True, null=True, upload_to='correction_requests/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='المرفق المقترح')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تم الاعتماد'), ('returned', 'أعيد للمشرف'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('admin_note', models.TextField(blank=True, verbose_name='ملاحظة الإدارة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('principal_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='staffdata.principalrecord', verbose_name='سجل المدير/المديرة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffdata_reviewed_corrections', to=settings.AUTH_USER_MODEL, verbose_name='مراجع الطلب')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='accounts.supervisor', verbose_name='المشرف')),
                ('vice_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='staffdata.viceprincipalrecord', verbose_name='سجل الوكيل/الوكيلة')),
            ],
            options={
                'verbose_name': 'طلب تصحيح',
                'verbose_name_plural': 'طلبات التصحيح',
                'ordering': ['-created_at'],
            },
        ),
    ]
