# Generated by Django 6.0.4 on 2026-04-19 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_supervisor_is_activated_supervisor_last_login_at_and_more'),
        ('staffdata', '0002_correctionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد المعالجة'), ('processed', 'تمت المعالجة'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffdata_processed_account_reset_requests', to=settings.AUTH_USER_MODEL, verbose_name='تمت المعالجة بواسطة')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_reset_requests', to='accounts.supervisor', verbose_name='المشرف')),
            ],
            options={
                'verbose_name': 'طلب إعادة تهيئة حساب',
                'verbose_name_plural': 'طلبات إعادة تهيئة الحسابات',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('supervisor',), name='unique_pending_account_reset_request_per_supervisor')],
            },
        ),
    ]
