# Generated by Django 6.0.4 on 2026-04-19 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffdata', '0003_accountresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionrequest',
            name='requested_mobile',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='يجب أن يكون رقم الجوال بصيغة 05XXXXXXXX أو 9665XXXXXXXX.', regex='^(05\\d{8}|9665\\d{8})$')], verbose_name='رقم الجوال المقترح'),
        ),
        migrations.AddField(
            model_name='principalrecord',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='يجب أن يكون رقم الجوال بصيغة 05XXXXXXXX أو 9665XXXXXXXX.', regex='^(05\\d{8}|9665\\d{8})$')], verbose_name='رقم الجوال'),
        ),
        migrations.AddField(
            model_name='viceprincipalrecord',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='يجب أن يكون رقم الجوال بصيغة 05XXXXXXXX أو 9665XXXXXXXX.', regex='^(05\\d{8}|9665\\d{8})$')], verbose_name='رقم الجوال'),
        ),
    ]
