# Generated by Django 6.0.4 on 2026-04-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffdata', '0004_correctionrequest_requested_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntryWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='فترة تسجيل البيانات', max_length=200, verbose_name='اسم الفترة')),
                ('starts_at', models.DateTimeField(verbose_name='بداية الفترة')),
                ('ends_at', models.DateTimeField(verbose_name='نهاية الفترة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('allow_add', models.BooleanField(default=True, verbose_name='السماح بالإضافة')),
                ('allow_edit', models.BooleanField(default=False, verbose_name='السماح بالتعديل')),
                ('allow_delete', models.BooleanField(default=False, verbose_name='السماح بالحذف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'فترة تسجيل البيانات',
                'verbose_name_plural': 'فترات تسجيل البيانات',
                'ordering': ['-starts_at'],
            },
        ),
    ]
