# Generated by Django 6.0.4 on 2026-04-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffdata', '0005_dataentrywindow'),
    ]

    operations = [
        migrations.AddField(
            model_name='principalrecord',
            name='assignment_status',
            field=models.CharField(choices=[('رسمي', 'رسمي'), ('مسير', 'مسير')], default='رسمي', max_length=10, verbose_name='الحالة الإدارية'),
        ),
    ]
