# Generated by Django 6.0.4 on 2026-04-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='اسم المشرف')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='السجل المدني')),
                ('password', models.CharField(max_length=255, verbose_name='كلمة المرور')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'مشرف',
                'verbose_name_plural': 'المشرفون',
                'ordering': ['full_name'],
            },
        ),
    ]
