# Generated by Django 6.0.4 on 2026-04-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='تم تفعيل الحساب'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر دخول'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='password_set_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إنشاء/تحديث كلمة المرور'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='كلمة المرور'),
        ),
    ]
