# Generated by Django 6.0.4 on 2026-04-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_supervisor_is_activated_supervisor_last_login_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='can_add_records',
            field=models.BooleanField(default=True, verbose_name='يستطيع إضافة السجلات'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='can_delete_records',
            field=models.BooleanField(default=False, verbose_name='يستطيع حذف السجلات'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='can_edit_records',
            field=models.BooleanField(default=False, verbose_name='يستطيع تعديل السجلات'),
        ),
    ]
