# Generated by Django 6.0.4 on 2026-04-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_supervisor_can_add_records_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='القطاع'),
        ),
    ]
